language: ruby
version: ~> 1.0
os: linux
sudo: false
bundler_args: --without development system_tests --path vendor

addons:
  apt:
    packages:
      # provides unbuffer
      - expect-dev
      - libaugeas-dev
      - augeas-tools

rvm:
  - 2.5.8
notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
# base env
  # Test latest Puppet 5 version
  - PUPPET=5.5 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
  # Test latest Puppet version
  - PUPPET=6 RUBY_AUGEAS=0.5
  - PUPPET=7 RUBY_AUGEAS=0.5

matrix:
  fast_finish: true

script:
  - AUGEAS_LENS_LIB=lib/augeas/lenses:augeas/lenses travis_wait 45 unbuffer bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: "My4qO46r6P/i4ColES0WF5OJ7Oyzp+Y86uVFH8YUDCxLAymX0T96wTwKxZcfIcEjItx687ucEqKwiVuuhRm4/QbxFB85XhqySzE9TqN7iT+fsHggSlYC57XwThHrPKxCk1fKCsAAKYH5qeS94Wy9FAaiB4yknmrBO9e7EFmVqOo="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.4.4
    condition: "$FORGE_PUBLISH = true"
