HOSTS:
  el7:
    roles:
      - default
      - grub2
    platform:   el-7-x86_64
    box:        generic/centos7
    hypervisor: vagrant

  el8:
    roles:
      - grub2
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  puppet_collection: puppet6
  ## vb_gui: true
